service/sistema/municipio/models.py
from sistema import app, db

MunicipioxEmpresa = db.Table(
    'municipioxempresa',
    db.Column('id_municipio', db.Integer, db.ForeignKey('municipio.id')),
    db.Column('id_empresa', db.Integer, db.ForeignKey('empresa.id')))


class Municipio(db.Model):
    __tablename__ = "municipio"

    id = db.Column(db.Integer, primary_key=True)
    id_ibge = db.Column(db.Integer, nullable=True)
    nome = db.Column(db.String(30), nullable=False)
    nome_formatado = db.Column(db.String(30), nullable=True)
    url_site_prefeitura = db.Column(db.String(50), nullable=True)
    url_portal = db.Column(db.String(50), nullable=True)

    empresa = db.relationship("Empresa",
                                 secondary=MunicipioxEmpresa,
                                 back_populates="municipios")

service/sistema/municipio/views.py
import os
import pandas as pd
import numpy as np
from sistema.municipio.manage_municipios import formatar_nome_de_municipio
from sistema import db
from sistema.municipio import manage_municipios
from sistema.empresa.models import Empresa
from sistema.municipio.models import Municipio
from flask import Blueprint, render_template, request, redirect, url_for, current_app

municipio = Blueprint('municipio', __name__, template_folder="templates")

@municipio.route('/')
def index():
    municipios = Municipio.query.all()

    return render_template('municipio.html',
                           municipios=municipios,
                           segment='municipio')


@municipio.route('/carregar_municipios', methods=['GET'])
def carregar():

    dir_path = os.path.dirname(os.path.realpath(__file__))
    df = pd.read_csv(dir_path + '/links_validados.csv')

    Municipio.query.delete()

    # Coloca o id_ibge com base na lista_municipios.csv
    codigos_ibge = []
    df_municipios = pd.read_csv(dir_path + '/lista_municipios.csv', index_col='nome')

    for _, row in df.iterrows():
        nome_do_municipio = row['Município']
        municipio_com_codigo = df_municipios.loc[nome_do_municipio]
        codigo_ibge_do_municipio = municipio_com_codigo['id']
        codigos_ibge.append(municipio_com_codigo['id']) 
        print(codigo_ibge_do_municipio)

        nome_formatado = formatar_nome_de_municipio(row['Município']) 

        municipio = manage_municipios.inserir_municipios(nome=row['Município'],
                                            nome_formatado=nome_formatado,
                                            url_site_prefeitura=row['Site Prefeitura'],
                                            url_portal=row['Portal da Transparência (validado)'],
                                            id_ibge=int(codigo_ibge_do_municipio))

    df['id_ibge'] = codigos_ibge
    df.to_csv(dir_path + '/links_validados.csv', index=False)

    municipios = Municipio.query.all()

    return render_template('municipio.html',
                           municipios=municipios,
                           segment='municipio')


@municipio.route('/atribuir_empresa/<int:_id>', methods=['POST', 'GET'])
def atribuir_empresa(_id):
    municipio = Municipio.query.get_or_404(_id)
    empresas = Empresa.query.all()

    if request.method == 'POST':
        id_empresa = request.form['id_empresa']
        empresa = Empresa.query.get_or_404(id_empresa)
        municipio.empresa.append(empresa)

        db.session.commit()

        return redirect(url_for('municipio.perfil', _id=municipio.id))
    return render_template('atribuir_empresa.html',
                           municipio=municipio,
                           segment='municipio',
                           empresas=empresas)

@municipio.route('/perfil/<int:_id>', methods=['GET'])
def perfil(_id):
    municipio = Municipio.query.get_or_404(_id)

    return render_template('dados_municipio.html',
                           segment='municipio',
                           municipio=municipio)

service/src/empresa/views.py
import os
import json
from src import db
import pandas as pd
from flask import jsonify
from flask import Blueprint
from src.empresa.models import Empresa
from src.municipio.models import Municipio
from src.api_de_integracao.manage import formatar_nome
from src.empresa.manage import get_nome_dos_municipios_do_template_sem_formatar, get_nome_dos_templates

empresa = Blueprint('empresa', __name__)

@empresa.route('/')
def index():
    templates = get_nome_dos_templates()
    return jsonify(templates)


@empresa.route('/cadastrar_templates', methods=['GET'])
def cadastrar():
    """Cadastrar Templates
    Este endpoint cadastra os templates únicos do arquivo CSV 'municipios_clusters.csv' na tabela de templates.
    
    O arquivo 'municipios_clusters.csv' deve conter as seguintes colunas:
    
    | municipio    | template_name_size |
    | Belo Horizonte | template_1        |
    | Uberlândia    | template_2        |
    
    ---
    tags:
      - Gerênciamento do banco de dados
    responses:
      200:
        description: OK
    """

    Empresa.query.delete()

    # 1) Insere os templates unicos do csv 'municipios_clusters' na tabela de templates

    dir_path = os.path.dirname(os.path.realpath(__file__))
    df = pd.read_csv(dir_path + '/municipios_clusters.csv')

    nomes = df['template_name_size'].unique()

    for nome in nomes:
        if (pd.isna(nome)):
            nome = 'sem_template'
        nome = formatar_nome(nome)
        empresa = Empresa(nome=formatar_nome(nome))
        db.session.add(empresa)
    db.session.commit()

    # 2) Para cada municipio, associa o template.

    for _, row in df.iterrows():
        nome_do_municipio = row['municipio']
        nome_da_empresa = row['template_name_size']

        if (pd.isna(nome_da_empresa)):
            nome_da_empresa = 'sem_template'
        nome_da_empresa = formatar_nome(nome_da_empresa)

        municipio = Municipio.query.filter_by(nome=nome_do_municipio).all()[0]
        if (len(municipio.empresa) == 0):
            empresa = Empresa.query.filter_by(nome=nome_da_empresa).all()[0]
            municipio.empresa.append(empresa)

    db.session.commit()

    return jsonify('ok')


@empresa.route('/<string:nome_do_template>', methods=['GET'])
def municipios_do_template(nome_do_template):
    """Municípios do Template
    Este endpoint retorna os nomes dos municípios associados a um determinado template.    
    ---
    tags:
      - Consultas no banco de dados
    parameters:
      - name: nome_do_template
        in: path
        type: string
        required: true
        description: O nome do template a ser consultado.
        enum:
          - sintese_tecnologia_e_informatica_88
          - memory_66
          - portaltp_61
          - siplanweb_61
          - portal_facil_60
          - portal_facil_46
          - pt_45
          - template2_28
          - grp_27
          - betha_26
          - adpm_22
          - template1_22
          - abo_21
          - municipal_net_11
          - template1_9
          - adpm_7
          - betha_7
          - e-cidade_7
          - fiorilli_sociedade_civil_7
          - habeas_data_7
          - horusdm_7
          - memory_6
          - portaltransp_6
          - ipm_sistemas_5
          - municipio_web_5
          - portal_facil_5
          - tecnologia_global_sistemas_5
          - template3_5
          - dardani_sistemas_4
          - govbr_4
          - sem_template
    responses:
      200:
        description: OK
    """
    return jsonify(get_nome_dos_municipios_do_template_sem_formatar(nome_do_template))


# Gerar jsons com os nomes de múnicipios de cara template. Usado no gerador de issues
@empresa.route('/gerar_jsons', methods=['POST', 'GET'])
def gerar_jsons():
    templates = Empresa.query.all()
    if len(templates):
        templates = [template.nome for template in templates]
    for nome_do_template in templates:
        with open(os.getcwd() + f"/src/empresa/municipios/{nome_do_template}.json", "w", encoding="utf-8") as outfile:
            print(get_nome_dos_municipios_do_template_sem_formatar(nome_do_template))
            json_object = json.dumps(get_nome_dos_municipios_do_template_sem_formatar(
                nome_do_template), indent=4, ensure_ascii=False)
            outfile.write(json_object)

    return jsonify('ok')

service/sistema/municipio/templates/perfil_municipio.html
{% extends 'layouts/base.html' %}

{% block title %}
Perfil - {{municipio.nome}}
{% endblock title %}

{% block content %}

<div class="content">
    <div class="panel-header bg-primary-gradient">
        <div class="page-inner py-5">
            <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                <div>
                    <h2 class="text-white pb-2 fw-bold">{{municipio.nome}}

                        <!-- <div class="avatar avatar-xl">
                            <img src="/static/fotos/{{municipio.foto}}" alt="..." class="avatar-img rounded-circle ml-3">
                        </div> -->
                    </h2>
                    <h5 class="text-white op-7 mb-2">Visão geral</h5>
                </div>
                <div class="ml-md-auto py-2 py-md-0">
                    {% if municipio.empresa|length == 0 %}
                    <a href="{{url_for('municipio.atribuir_empresa', _id=municipio.id)}}"
                        class="btn btn-white  btn-round mr-2"><span class="btn-label mr-2"> <i
                                class="fa fa-plus-circle"></i></span>Template</a>
                    {% endif %}
                    <a href="{{url_for('municipio.index')}}" class="btn btn-default  btn-round mr-2"><span
                            class="btn-label mr-1"><i class="fas fa-users"></i></span> Municípios</a>
                    
                    <a href="{{url_for('municipio.editar_municipio',_id=municipio.id)}}"
                            class="btn btn-info btn-border btn-round">
                            <span class="btn-label">
                                <i class="fas fa-edit"></i>
                            </span>
                            Editar
                    </a>

                    <a href="{{url_for('municipio.excluir_municipio',_id=municipio.id)}}" class="btn btn-danger btn-round">
                        <span class="btn-label mr-1"><i class="fas fa-trash"></i></span>Excluir </a>
                </div>
            </div>
        </div>
    </div>
    <div class="page-inner mt--5">
        <div class="row mt--2">
            <div class="col-md-8">
                <div class="card full-height">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-head-row">
                                <div class="card-title">Coletas:</div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="chart-container">
                                <label for="nome">Servidores:</label>
                                <h5 class="displayIB" id="nome">asdas</h5>
                                <br>
                                <label for="felicidade"> Licitações:</label>
                                <h5 class="displayIB" id="nome">asdas</h5>
                                <br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">Estatísticas do município</div>
                        <div class="card-category"></div>
                        <div class="d-flex flex-wrap justify-content-around pb-2 pt-4">
                            <div class="px-2 pb-2 pb-md-0 text-center">
                                <div id="circles-1"></div>
                                <h6 class="fw-bold mt-3 mb-0">Itens coletados</h6>
                            </div>
                            <div class="px-2 pb-2 pb-md-0 text-center">
                                <div id="circles-2"></div>
                                <h6 class="fw-bold mt-3 mb-0">Itens validados</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        {% if municipio.empresa|length %}
        <div class=" row row-card-no-pd">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-head-row card-tools-still-right">
                            <h4 class="card-title">Template</h4>
                            <div class="card-tools">
                                {% for empresa in municipio.empresa %}
                                <a href="{{url_for('municipio.remover_empresa',_id_cidadao=municipio.id,_id_empresa=empresa.id)}}"
                                    class="btn btn-danger btn-round btn-border">
                                    <span class="btn-label mr-2"><i class="fas fa-trash"></i></span>Remover do
                                    template</a>
                                {% endfor %}
                            </div>
                        </div>
                        <p class="card-category">
                            {{municipio.nome}} faz parte do 
                            {% for empresa in municipio.empresa %}
                                <a href="{{url_for('empresa.perfil',_id_empresa=empresa.id)}}">{{empresa.nome}}</a>
                            {% endfor %}
                        </p>
                    </div>

                    <!-- CASO TENHA MAIS DE UM TEMPLATE POR MUNICIPIO -->
                    <!-- <div class="card-body">
                        <div class="table-responsive table-hover table-sales">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Total de municipios</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for empresa in municipio.empresa %}
                                    <tr>
                                        <td><a
                                                href="{{url_for('empresa.perfil',_id_empresa=empresa.id)}}">{{empresa.nome}}</a>
                                        </td>
                                        <td>{{empresa.tipo}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
        {% endif %}
        {% if municipio.empresa|length == 0 %}
        <a class="btn btn-primary btn-lg btn-block"
            href="{{url_for('municipio.atribuir_empresa', _id=municipio.id)}}">Atribuir
            Template</a>
        {% endif %}
    </div>
</div>

{% endblock content %}


{% block javascripts %}

<script>
    var itens_coletados = '{{municipio.itens_coletados}}';
    Circles.create({
        id: 'circles-1',
        radius: 45,
        value: itens_coletados,
        maxValue: 10,
        width: 7,
        text: itens_coletados,
        colors: ['#f1f1f1', '#33b0b5'],
        duration: 10,
        wrpClass: 'circles-wrp',
        textClass: 'circles-text',
        styleWrapper: true,
        styleText: true
    })

    var itens_validados = '{{municipio.itens_validados}}';
    Circles.create({
        id: 'circles-2',
        radius: 45,
        value: itens_validados,
        maxValue: 10,
        width: 7,
        text: itens_validados,
        colors: ['#f1f1f1', '#33b0b5'],
        duration: 10,
        wrpClass: 'circles-wrp',
        textClass: 'circles-text',
        styleWrapper: true,
        styleText: true
    })

</script>

{% endblock javascripts %}